import type { AdminOrder, AdminProduct } from "@/modules/admin/types"

export const adminProductsMock: AdminProduct[] = [
  {
    id: "p-001",
    image: "/lg-split-air-conditioner-white-modern.jpg",
    name: "LG Dual Inverter 12000 BTU",
    brand: "LG",
    type: "split",
    btu: "12000",
    price: 599.99,
    salePrice: 549.99,
    stock: 21,
    status: "active",
    rating: 4.8,
    sku: "LG-INV-12K",
    inverter: true,
    wifi: true,
    energy: "A+++",
    description: "Equipo silencioso y eficiente para recámaras y oficinas medianas.",
    tags: ["inverter", "wifi", "best-seller"],
    slug: "lg-dual-inverter-12000-btu",
    metaTitle: "LG Dual Inverter 12000 BTU | Aire-Max",
    metaDescription: "Aire acondicionado LG inverter 12000 BTU con WiFi y alta eficiencia energética.",
  },
  {
    id: "p-002",
    image: "/samsung-split-air-conditioner-sleek-design.jpg",
    name: "Samsung WindFree 18000 BTU",
    brand: "Samsung",
    type: "split",
    btu: "18000",
    price: 799.99,
    stock: 7,
    status: "active",
    rating: 4.6,
    sku: "SAM-WF-18K",
    inverter: true,
    wifi: true,
    energy: "A++",
    description: "Confort sin corrientes directas, ideal para sala-comedor.",
    tags: ["windfree", "premium"],
    slug: "samsung-windfree-18000-btu",
    metaTitle: "Samsung WindFree 18000 BTU | Aire-Max",
    metaDescription: "Confort premium WindFree con tecnología inverter y control WiFi.",
  },
  {
    id: "p-003",
    image: "/daikin-split-air-conditioner-premium.jpg",
    name: "Daikin Smart Cassette 24000 BTU",
    brand: "Daikin",
    type: "cassette",
    btu: "24000",
    price: 1199.99,
    salePrice: 1099.99,
    stock: 3,
    status: "active",
    rating: 4.9,
    sku: "DAI-CAS-24K",
    inverter: true,
    wifi: false,
    energy: "A+++",
    description: "Solución comercial con distribución uniforme de aire.",
    tags: ["comercial", "cassette"],
    slug: "daikin-smart-cassette-24000-btu",
    metaTitle: "Daikin Cassette 24000 BTU | Aire-Max",
    metaDescription: "Cassette comercial Daikin 24000 BTU para espacios de alto tráfico.",
  },
  {
    id: "p-004",
    image: "/modern-air-conditioning-unit-installation-professi.jpg",
    name: "Midea Ventana Eco 9000 BTU",
    brand: "Midea",
    type: "ventana",
    btu: "9000",
    price: 399.99,
    stock: 0,
    status: "inactive",
    rating: 4.2,
    sku: "MID-VEN-9K",
    inverter: false,
    wifi: false,
    energy: "A+",
    description: "Opción económica para espacios reducidos.",
    tags: ["entry-level"],
    slug: "midea-ventana-eco-9000-btu",
    metaTitle: "Midea Ventana 9000 BTU | Aire-Max",
    metaDescription: "Equipo de ventana económico y compacto para uso residencial.",
  },
]

export const adminOrdersMock: AdminOrder[] = [
  {
    id: "ORD-2301",
    customer: "Carla Méndez",
    items: 2,
    total: 1499.98,
    status: "Pendiente",
    createdAt: "2026-03-27",
  },
  {
    id: "ORD-2302",
    customer: "Grupo Áurea",
    items: 4,
    total: 4399.96,
    status: "Procesando",
    createdAt: "2026-03-27",
  },
  {
    id: "ORD-2303",
    customer: "Nicolás Ramos",
    items: 1,
    total: 549.99,
    status: "Enviado",
    createdAt: "2026-03-26",
  },
]
